<?php 
$tableParams = array(
	'tableId' 			=> 'samples-custom-table',
    'tableWidth'        => '4',
);
?>

<?php echo $this->zrayTable($tableParams); //zrayTableHtml ?>

<script type="text/javascript">
(function() {
	var storage = zray.getStorage('samplesCustomTable');

	// create main table
	var maintable = zray.createTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
	maintable.setColumns([
		{
			"label": "The Name",
			"propertyName": "name",
			"sortable": true,
			"width": '20%',
			"getHtml": function(value, record) {
				return 'Name is <b>' + value + '</b>';
			}		
		},
		{
			"label": "The Version",
			"propertyName": "version",
			"sortable": true,
			"width": '20%',
			"getHtml": function(value, record) {
				return 'Latest version <u>' + value + '</u>';
			}		
		},
		{
			"label": "The Developer",
			"propertyName": "developer",
			"sortable": true,
			"width": '20%',
			"getHtml": function(value, record) {
				return '<u>' + value + '</u> is the developer';
			}		
		},
		{
			"label": "The OS",
			"propertyName": "os",
			"sortable": true,
			"width": '40%',
			"getHtml": function(value, record) {
				var elem = jQuery('<span>' + value + ' (click)</span>');
				elem.click(function() {
					alert('You clicked ' + value);
				});
				return elem;
			}	
		}
	]);
	// create main table - end

	// create pager and search
	zray.createPager(storage, jQuery('#<?php echo $params['pagerId']; ?>'));
	zray.createSearch(storage, jQuery('#<?php echo $params['searchId']; ?>'), maintable);
	
	zray.registerDataHandler('samples', 'defaultTable', function(extensionData, requestData) {
		storage.setData(extensionData);
	});
})();
</script>